DROP SCHEMA IF EXISTS scry CASCADE;
CREATE SCHEMA scry;
SET search_path = scry;

CREATE TABLE authors (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE books (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  author_id int8 REFERENCES authors (id)
);

CREATE TABLE series (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE series_books (
  series_id int8 REFERENCES series (id),
  book_id int8 REFERENCES books (id)
);


INSERT INTO authors (id, name) VALUES
  (1, 'J.R.R Tokien'),
  (2, 'J.K. Rowling'),
  (3, 'Ted Chaing');

INSERT INTO books (id, title, author_id) VALUES
  (1, 'Fellowship of the Rings', 1),
  (2, 'The Two Towers', 1),
  (3, 'Return of the King', 1),
  (4, 'Harry Potter and the Philosopher''s Stone', 2),
  (5, 'Harry Potter and the Prisoner of Azkaban', 2),
  (6, 'Exhalation', 3);


INSERT INTO series (id, name) VALUES
  (1, 'Lord of the Rings'),
  (2, 'Harry Potter');

INSERT INTO series_books (series_id, book_id) VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 4),
  (2, 5)
